### ISSUE TITLE
How complete is this? What feature-critical parts can I contribute to?

### ISSUE THREAD

**Issue by seankhl** [dskinner/material#13]
I'm writing a very simple password manager in go and would like to develop an android app for it. I would like to stick to pure go. Since the app will be extremely simple, I think I may be able to use your library for it. I will basically need things like a lists of sites (that have associated usernames/passwords etc), press and hold menus for elements of those lists, master password entry, etc. It may be a good test case for the library and I could help contribute some components that would be necessary if they don't exist.

Let me know where you are in the development and how this sounds, and hopefully I can help contribute to your library.

**Comment by dskinner** [comment]
Sorry for the late reply, though I'm sure you've moved on by now. I'm tagging this project discontinued but thanks for your interest at the time.
