### ISSUE TITLE
Can't run demos but can run general gomobile demos

### ISSUE THREAD

**Issue by lostinblue** [dskinner/material#7]
Any suggestions on how to debug this? I inspected logcat but I can not see anything useful. I would love to help out with this library.

**Comment by joeblew99** [comment]
Not sure if this helps but a few days ago I ran your code on OSX and android. No issues at all.
So demos run on OSX it case you are not on a Mac.

Are you wanting to debug it though as in using delve ?
I have found delve debugging to not be very helpful in the golang world.

**Comment by dskinner** [comment]
@lostinblue Can you describe the issue in more detail?

* did you follow the README for each example and copy in assets? to correct directory?
* can you run the examples on desktop? (just use `go run main.go`) Also, what is your host OS (this may not work on windows, haven't tried)?
* what is the make/model and android version of your mobile device?

With that said, I have had one report of a galaxy note 2 running 4.4.3 which only displays the color from clearing the screen, but has no issue with the gomobile examples. Unfortunately, I don't have access to the device or a way to remotely debug the issue :\ Nor can I reproduce the issue on any of my own devices. So, if this is what you're seeing it'd be fantastic if you could assist in identifying the fault by first confirming some of the info above.

**Comment by lostinblue** [comment]
I'm using linux to build the packages. Sorry I should have been clear, the packages build but then they simply do not run on my android device. They open and immediately close.

I will see try another android device to see if that is the root cause. I appreciate the quick response, hopefully once I get this working I can help contribute to the library.

**Comment by lostinblue** [comment]
I got the text demo working on the original device, still working out the issue with the boxes. I had changed a lot of libraries so I'm not exactly sure which fixed it. I will go ahead and close this.

**Comment by lostinblue** [comment]
`ActivityManager(  513): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity} from pid 789
I/ActivityManager(  513): Start proc cc.dasa.material.example.boxes for activity cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity: pid=17117 uid=10085 gids={50085}
V/ActivityManager(  513): Binding process pid 17117 to record ProcessRecord{417274c0 17117:cc.dasa.material.example.boxes/u0a10085}
V/ActivityManager(  513): New app record ProcessRecord{417274c0 17117:cc.dasa.material.example.boxes/u0a10085} thread=android.os.BinderProxy@41d4a578 pid=17117
V/ActivityManager(  513): ACT-Launching: ActivityRecord{41c03d00 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity}
W/ActivityThread(17117): Application cc.dasa.material.example.boxes can be debugged on port 8100...
V/WindowManager(  513): Changing focus from null to Window{41d9b270 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity}
I/WindowManager(  513): Gaining focus: Window{41d9b270 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity}
I/ActivityManager(  513): Process cc.dasa.material.example.boxes (pid 17117) has died.
W/ActivityManager(  513): Force removing ActivityRecord{41c03d00 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity}: app died, no saved state
I/WindowState(  513): WIN DEATH: Window{41d9b270 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity}
V/WindowManager(  513): Changing focus from Window{41d9b270 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity} to null
I/WindowManager(  513): Losing focus: Window{41d9b270 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity}
D/Launcher(  789): Start Activity >>> ComponentInfo{cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity}
I/ActivityManager(  513): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity} from pid 789
I/BufferQueue(  130): [Starting cc.dasa.material.example.boxes](this:0x41e91e80,api:0) setConsumerName: Starting cc.dasa.material.example.boxes
I/BufferQueue(  130): [Starting cc.dasa.material.example.boxes](this:0x41e91e80,api:0) setDefaultBufferSize: w=540, h=960
D/        (  789): Logging application : ComponentInfo{cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity} : 11
D/        (  789): FairPhone - Qs : 6 : Most Used : Adding ComponentInfo{cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity} to position 3
I/BufferQueue(  130): [Starting cc.dasa.material.example.boxes](this:0x41e91e80,api:0) connect: api=2
I/BufferQueue(  130): [Starting cc.dasa.material.example.boxes](this:0x41e91e80,api:2) setSynchronousMode: enabled=1
I/BufferQueue(  130): [Starting cc.dasa.material.example.boxes](this:0x41e91e80,api:2) new GraphicBuffer needed
I/SurfaceTexture(  130): [Starting cc.dasa.material.example.boxes](this:0x41e928f0,api:2) [void* android::SurfaceTexture::createImage(EGLDisplay, const android::sp<android::GraphicBuffer>&)]
I/ActivityManager(  513): Start proc cc.dasa.material.example.boxes for activity cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity: pid=17160 uid=10085 gids={50085}
V/ActivityManager(  513): Binding process pid 17160 to record ProcessRecord{41781a00 17160:cc.dasa.material.example.boxes/u0a10085}
V/ActivityManager(  513): New app record ProcessRecord{41781a00 17160:cc.dasa.material.example.boxes/u0a10085} thread=android.os.BinderProxy@41568bc8 pid=17160
I/BufferQueue(  130): [Starting cc.dasa.material.example.boxes](this:0x41e91e80,api:2) setDefaultBufferSize: w=960, h=540
V/ActivityManager(  513): ACT-Launching: ActivityRecord{41445608 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity}
W/ActivityThread(17160): Application cc.dasa.material.example.boxes can be debugged on port 8100...
D/dalvikvm(17160): open_cached_dex_file : /data/app/cc.dasa.material.example.boxes-1.apk /data/dalvik-cache/data@app@cc.dasa.material.example.boxes-1.apk@classes.dex
D/dalvikvm(17160): Trying to load lib /data/app-lib/cc.dasa.material.example.boxes-1/libboxes.so 0x412cbe58
D/dalvikvm(17160): Added shared lib /data/app-lib/cc.dasa.material.example.boxes-1/libboxes.so 0x412cbe58
I/BufferQueue(  130): [cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity](this:0x41e96388,api:0) setConsumerName: cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity
V/WindowManager(  513): Changing focus from null to Window{41bfd750 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity}
I/BufferQueue(  130): [cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity](this:0x41e96388,api:0) setDefaultBufferSize: w=960, h=540
I/WindowManager(  513): Gaining focus: Window{41bfd750 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity}
I/BufferQueue(  130): [cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity](this:0x41e96388,api:0) connect: api=1
I/BufferQueue(  130): [cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity](this:0x41e96388,api:1) setSynchronousMode: enabled=1
I/BufferQueue(  130): [cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity](this:0x41e96388,api:1) setSynchronousMode: enabled=1
I/BufferQueue(  130): [cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity](this:0x41e96388,api:1) new GraphicBuffer needed
I/WindowState(  513): WIN DEATH: Window{41bfd750 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity}
I/ActivityManager(  513): Process cc.dasa.material.example.boxes (pid 17160) has died.
W/ActivityManager(  513): Force removing ActivityRecord{41445608 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity}: app died, no saved state
I/BufferQueue(  130): [cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity](this:0x41e96388,api:1) consumerDisconnect
I/BufferQueue(  130): [cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity](this:0x41e96388,api:1) ~BufferQueue
V/WindowManager(  513): Changing focus from Window{41bfd750 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity} to null
I/WindowManager(  513): Losing focus: Window{41bfd750 u0 cc.dasa.material.example.boxes/org.golang.app.GoNativeActivity}
I/BufferQueue(  130): [Starting cc.dasa.material.example.boxes](this:0x41e91e80,api:2) disconnect: api=2
I/SurfaceTexture(  130): [Starting cc.dasa.material.example.boxes] [virtual android::status_t android::SurfaceTexture::forceAuxConversionLocked()] mCurrentTexture:0, mCurrentBuf:0x42304e90
I/BufferQueue(  130): [Starting cc.dasa.material.example.boxes](this:0x41e91e80,api:0) getReleasedBuffers: returning mask 0xffffffff
I/SurfaceTexture(  130): [Starting cc.dasa.material.example.boxes](this:0x41e928f0,api:0) destroying EGLImage dpy=0x1 img=0x41e92f18
I/BufferQueue(  130): [Starting cc.dasa.material.example.boxes](this:0x41e91e80,api:0) consumerDisconnect
I/BufferQueue(  130): [Starting cc.dasa.material.example.boxes](this:0x41e91e80,api:0) ~BufferQueue`

**Comment by lostinblue** [comment]
So it does not crash when I comment out a single line:

    //env.LoadGlyphs(ctx)

Any guesses what would be causing this issue?

**Comment by dskinner** [comment]
I mistakenly committed changes to the example that show text, requiring the same texture file from the text example. For now, the boxes example should just be boxes.

**Comment by lostinblue** [comment]
Ah, that explains it. Well glad I could help point that out. I look forward to using this library, I really like the spec for meterial.
