### ISSUE TITLE
Creating more examples

### ISSUE THREAD

**Issue by lostinblue** [dskinner/material#8]
I was thinking it would make good practice to create examples. It would be helpful for others who are interested in learning more about material and this library if more examples. 

Do you have any examples possibly from the material docs you would like to see implemented?

**Comment by lostinblue** [comment]
I'm working on a simple drag and drop example. I feel like that would be the next obvious example. Why does the Touch function under env not return the touched object? Wouldn't that require me the recreate the same code within Touch inside my program to obtain the touched object?

**Comment by dskinner** [comment]
> I was thinking it would make good practice to create examples.

I think it's still too early to be creating many examples but if I were to pick one, it'd be the top video from here: https://www.google.com/design/spec/motion/material-motion.html

That's mostly just plain material and lots of animation, and a similar demo would be a great way to stress the current implementation of material, shadows, animation, and the api overall to identify how things could be better with the most basic things.

> I'm working on a simple drag and drop example.

Current touch is just a stand in for establishing things like hit testing and radial animation.

Drag and drop would be nice but it's part of a larger framework that needs to be written to provide everything discussed here: https://www.google.com/design/spec/patterns/gestures.html

This would likely be defined as some kind of `GestureDetector` that can receive and interpret the touch events, and then emit the appropriate gesture event.

If you're interested in working on this, I'd suggest reviewing the link above for all the gestures to support (there's various types of drags for example) and also possibly reviewing how such things are handled in other frameworks before proceeding, for example https://developer.android.com/reference/android/view/GestureDetector.html

**Comment by lostinblue** [comment]
Thanks for your patience and additional information. I will read more through the Material spec and try to get a better understanding. Do you have a road map of what features are done and what features you would need to complete to creating an example of the material spec?

**Comment by dskinner** [comment]
I'll try and put together a better roadmap within the next week or so. I wouldn't call any part complete just yet. Currently my focus has to do with layout which encompasses a lot of parts including the display of text, images, scrolling, responsive design, etc

> Are all gestures mobile only? How would mouse interaction be integrated if touch, drag, swipe, and fling are mobile only.

That's an open question. At bare minimum, use of gomobile will generate touch events on desktop allowing for any gesture that uses one finger to fire on desktop, but further down desktops of course have right click, etc.

A GestureDetector is actually pretty high on my TODO list though it's still probably months out before I'll have the time to start on it and it should be able to be written without too much regard to other on-going work since it's a mostly non-visual task.

**Comment by lostinblue** [comment]
My initial goal is to use the library to create a mobile UI for essentially an instant messenger program (it is an example project for a protocol I'm working on). For my purposes I need to get input/interactions/gestures working. I will study that part of the spec and see if I can sketch out the basic building blocks but if you think there are other parts that need to be completed first please let me know.

**Comment by lostinblue** [comment]
Would you be willing to change the touch function to return the object instead of a bool so I can use buttons in the example? Then I could create play buttons for the movement examples.

**Comment by dskinner** [comment]
I'm not sure the touch function is even going to stick around, so if you want to alter it as an easy way in to get started, feel free to.

**Comment by lostinblue** [comment]
I will go ahead and close this because I think I would rather just help directly work on it rather than make examples at this point. I did not fully understand how far a long the project was.
